/**
 * Gauteng suburb → municipality lookup.
 * Checked in order — first match wins.
 * Returns null if the address doesn't match any known suburb.
 */

const LOOKUP: Array<[string, string]> = [
  // ── Tshwane ──────────────────────────────────────────────────
  ['pretoria',        'Tshwane'],
  ['centurion',       'Tshwane'],
  ['soshanguve',      'Tshwane'],
  ['mamelodi',        'Tshwane'],
  ['atteridgeville',  'Tshwane'],
  ['silverton',       'Tshwane'],
  ['hatfield',        'Tshwane'],
  ['arcadia',         'Tshwane'],
  ['sunnyside',       'Tshwane'],
  ['groenkloof',      'Tshwane'],
  ['waterkloof',      'Tshwane'],
  ['lynnwood',        'Tshwane'],
  ['menlo park',      'Tshwane'],
  ['garsfontein',     'Tshwane'],
  ['faerie glen',     'Tshwane'],
  ['moreleta park',   'Tshwane'],
  ['montana',         'Tshwane'],
  ['brooklyn',        'Tshwane'],
  ['ashlea gardens',  'Tshwane'],
  ['erasmusrand',     'Tshwane'],
  ['rietvalleirand',  'Tshwane'],
  ['sinoville',       'Tshwane'],
  ['wonderboom',      'Tshwane'],
  ['karenpark',       'Tshwane'],
  ['akasia',          'Tshwane'],
  ['doornpoort',      'Tshwane'],
  ['equestria',       'Tshwane'],
  ['olympus',         'Tshwane'],
  ['meyerspark',      'Tshwane'],
  ['queenswood',      'Tshwane'],
  ['eersterust',      'Tshwane'],
  ['annlin',          'Tshwane'],
  ['hesteapark',      'Tshwane'],
  ['the willows',     'Tshwane'],
  ['irene',           'Tshwane'],
  ['highveld',        'Tshwane'],
  ['clubview',        'Tshwane'],
  ['lyttelton',       'Tshwane'],
  ['eldoraigne',      'Tshwane'],
  ['wierda park',     'Tshwane'],
  ['doringkloof',     'Tshwane'],
  ['zwartkop',        'Tshwane'],
  ['midstream',       'Tshwane'],
  ['rooihuiskraal',   'Tshwane'],
  ['kungwini',        'Tshwane'],
  ['bronkhorstspruit','Tshwane'],

  // ── Ekurhuleni ───────────────────────────────────────────────
  ['kempton park',    'Ekurhuleni'],
  ['bedfordview',     'Ekurhuleni'],
  ['edenvale',        'Ekurhuleni'],
  ['germiston',       'Ekurhuleni'],
  ['benoni',          'Ekurhuleni'],
  ['boksburg',        'Ekurhuleni'],
  ['brakpan',         'Ekurhuleni'],
  ['springs',         'Ekurhuleni'],
  ['alberton',        'Ekurhuleni'],
  ['vosloorus',       'Ekurhuleni'],
  ['tembisa',         'Ekurhuleni'],
  ['daveyton',        'Ekurhuleni'],
  ['nigel',           'Ekurhuleni'],
  ['isando',          'Ekurhuleni'],
  ['jetpark',         'Ekurhuleni'],
  ['primrose',        'Ekurhuleni'],
  ['glen marais',     'Ekurhuleni'],
  ['modderfontein',   'Ekurhuleni'],
  ['sunward park',    'Ekurhuleni'],
  ['northmead',       'Ekurhuleni'],
  ['rynfield',        'Ekurhuleni'],
  ['farrarmere',      'Ekurhuleni'],
  ['lakefield',       'Ekurhuleni'],
  ['crystal park',    'Ekurhuleni'],
  ['dawn park',       'Ekurhuleni'],
  ['reiger park',     'Ekurhuleni'],
  ['eden park',       'Ekurhuleni'],
  ['atlas park',      'Ekurhuleni'],
  ['bartlett',        'Ekurhuleni'],
  ['OR tambo',        'Ekurhuleni'],
  ['o.r. tambo',      'Ekurhuleni'],

  // ── City of Johannesburg ──────────────────────────────────────
  ['sandton',         'City of Johannesburg'],
  ['randburg',        'City of Johannesburg'],
  ['roodepoort',      'City of Johannesburg'],
  ['soweto',          'City of Johannesburg'],
  ['midrand',         'City of Johannesburg'],
  ['fourways',        'City of Johannesburg'],
  ['bryanston',       'City of Johannesburg'],
  ['morningside',     'City of Johannesburg'],
  ['rosebank',        'City of Johannesburg'],
  ['parkhurst',       'City of Johannesburg'],
  ['greenside',       'City of Johannesburg'],
  ['linden',          'City of Johannesburg'],
  ['craighall',       'City of Johannesburg'],
  ['rivonia',         'City of Johannesburg'],
  ['sunninghill',     'City of Johannesburg'],
  ['kyalami',         'City of Johannesburg'],
  ['dainfern',        'City of Johannesburg'],
  ['douglasdale',     'City of Johannesburg'],
  ['northriding',     'City of Johannesburg'],
  ['honeydew',        'City of Johannesburg'],
  ['diepsloot',       'City of Johannesburg'],
  ['cosmo city',      'City of Johannesburg'],
  ['northgate',       'City of Johannesburg'],
  ['randpark ridge',  'City of Johannesburg'],
  ['weltevredenpark', 'City of Johannesburg'],
  ['florida',         'City of Johannesburg'],
  ['constantia kloof','City of Johannesburg'],
  ['turffontein',     'City of Johannesburg'],
  ['booysens',        'City of Johannesburg'],
  ['brixton',         'City of Johannesburg'],
  ['fordsburg',       'City of Johannesburg'],
  ['maboneng',        'City of Johannesburg'],
  ['doornfontein',    'City of Johannesburg'],
  ['yeoville',        'City of Johannesburg'],
  ['hillbrow',        'City of Johannesburg'],
  ['kensington',      'City of Johannesburg'],
  ['norwood',         'City of Johannesburg'],
  ['orange grove',    'City of Johannesburg'],
  ['linksfield',      'City of Johannesburg'],
  ['wynberg',         'City of Johannesburg'],
  ['alexandra',       'City of Johannesburg'],
  ['marlboro',        'City of Johannesburg'],
  ['paulshof',        'City of Johannesburg'],
  ['hyde park',       'City of Johannesburg'],
  ['gallo manor',     'City of Johannesburg'],
  ['parktown',        'City of Johannesburg'],
  ['melville',        'City of Johannesburg'],
  ['lenasia',         'City of Johannesburg'],
  ['eldorado park',   'City of Johannesburg'],
  ['ennerdale',       'City of Johannesburg'],
  ['naturena',        'City of Johannesburg'],
  ['kibler park',     'City of Johannesburg'],
  ['glenvista',       'City of Johannesburg'],
  ['mulbarton',       'City of Johannesburg'],
  ['johannesburg',    'City of Johannesburg'],
  ['jozi',            'City of Johannesburg'],
  ['waterfall',       'City of Johannesburg'],
  ['ivory park',      'City of Johannesburg'],

  // ── Mogale City ───────────────────────────────────────────────
  ['krugersdorp',     'Mogale City'],
  ['magaliesburg',    'Mogale City'],
  ['muldersdrift',    'Mogale City'],
  ['hekpoort',        'Mogale City'],
  ['kagiso',          'Mogale City'],

  // ── Rand West ─────────────────────────────────────────────────
  ['randfontein',     'Rand West'],
  ['westonaria',      'Rand West'],

  // ── Emfuleni ──────────────────────────────────────────────────
  ['vereeniging',     'Emfuleni'],
  ['vanderbijlpark',  'Emfuleni'],
  ['sebokeng',        'Emfuleni'],
  ['evaton',          'Emfuleni'],
  ['three rivers',    'Emfuleni'],

  // ── Midvaal ───────────────────────────────────────────────────
  ['meyerton',        'Midvaal'],
  ['henley on klip',  'Midvaal'],

  // ── Lesedi ────────────────────────────────────────────────────
  ['heidelberg',      'Lesedi'],
  ['devon',           'Lesedi'],

  // ── Merafong ──────────────────────────────────────────────────
  ['carletonville',   'Merafong'],
]

export function detectMunicipality(address: string): string | null {
  const lower = address.toLowerCase()
  for (const [suburb, municipality] of LOOKUP) {
    if (lower.includes(suburb.toLowerCase())) return municipality
  }
  return null
}

export const MUNICIPALITIES = [
  'City of Johannesburg',
  'Ekurhuleni',
  'Tshwane',
  'Rand West',
  'Mogale City',
  'Emfuleni',
  'Midvaal',
  'Lesedi',
  'Merafong',
  'Other',
]
