import Link from 'next/link'
import Image from 'next/image'
import { createClient } from '@/lib/supabase/server'
import { Badge } from '@/components/ui/badge'
import { PlugZap, Package } from 'lucide-react'
import { formatCurrency } from '@/lib/utils'
import type { EquipmentRelationshipType } from '@/types/database'

// Section headings per relationship type. `forward` labels the section on the
// item's own page ("this inverter → compatible batteries"); `reverse` labels
// it on the related item's page ("this battery → works with these inverters").
const TYPE_LABELS: Record<string, { forward: string; reverse: string }> = {
  battery_for_inverter:    { forward: 'Compatible batteries',        reverse: 'Works with these inverters' },
  breaker_for_inverter:    { forward: 'AC breakers sized for this inverter', reverse: 'Sized for these inverters' },
  changeover_for_inverter: { forward: 'Changeover switches',         reverse: 'Fits these inverters' },
  spd_for_inverter:        { forward: 'AC surge protection',         reverse: 'Protects these inverters' },
  dc_breaker_for_panel:    { forward: 'DC string breakers',          reverse: 'Protects strings of these panels' },
  dc_isolator_for_panel:   { forward: 'DC isolators',                reverse: 'Isolates strings of these panels' },
  string_fuse_for_panel:   { forward: 'gPV string fuses',            reverse: 'Fuses strings of these panels' },
  dc_spd_for_panel:        { forward: 'PV surge protection',         reverse: 'Protects strings of these panels' },
  spd_for_breaker:         { forward: 'Phase-matched surge protection', reverse: 'Pairs with these breakers' },
  changeover_for_breaker:  { forward: 'Changeover switches',         reverse: 'Pairs with these breakers' },
  other:                   { forward: 'Related products',            reverse: 'Related products' },
}

const TYPE_ORDER: EquipmentRelationshipType[] = [
  'battery_for_inverter', 'breaker_for_inverter', 'changeover_for_inverter',
  'spd_for_inverter', 'dc_breaker_for_panel', 'dc_isolator_for_panel',
  'string_fuse_for_panel', 'dc_spd_for_panel', 'spd_for_breaker',
  'changeover_for_breaker', 'other',
]

interface RelRow {
  item_id: string
  related_id: string
  relationship_type: string
  reason: string | null
  priority: number
}

interface StoreProduct {
  external_id: string
  slug: string
  name: string
  brand: string | null
  price: number
  images: string[] | null
}

interface Entry {
  type: string
  direction: 'forward' | 'reverse'
  reason: string | null
  priority: number
  product: StoreProduct
}

/**
 * "Works with" section — catalog-level compatibility links (equipment_relationships,
 * generated by the SANS rules engine in migration 092), filtered to items that are
 * actually purchasable on the store (active products mirror rows).
 */
export async function CompatibleProducts({ externalId }: { externalId: string }) {
  const supabase = await createClient()

  const [{ data: fwd }, { data: rev }] = await Promise.all([
    supabase
      .from('equipment_relationships')
      .select('item_id, related_id, relationship_type, reason, priority')
      .eq('item_id', externalId)
      .eq('active', true)
      .order('priority', { ascending: false })
      .limit(80),
    supabase
      .from('equipment_relationships')
      .select('item_id, related_id, relationship_type, reason, priority')
      .eq('related_id', externalId)
      .eq('active', true)
      .order('priority', { ascending: false })
      .limit(80),
  ])

  const forward = (fwd ?? []) as RelRow[]
  const reverse = (rev ?? []) as RelRow[]
  if (forward.length === 0 && reverse.length === 0) return null

  // Resolve the "other side" of every link to a store-visible product.
  const otherIds = Array.from(new Set([
    ...forward.map((r) => r.related_id),
    ...reverse.map((r) => r.item_id),
  ]))
  const { data: mirror } = await supabase
    .from('products')
    .select('external_id, slug, name, brand, price, images')
    .in('external_id', otherIds)
    .eq('active', true)
  const byExternal = new Map((mirror ?? []).map((p) => [p.external_id as string, p as StoreProduct]))

  const entries: Entry[] = []
  for (const r of forward) {
    const product = byExternal.get(r.related_id)
    if (product) entries.push({ type: r.relationship_type, direction: 'forward', reason: r.reason, priority: r.priority, product })
  }
  for (const r of reverse) {
    const product = byExternal.get(r.item_id)
    if (product) entries.push({ type: r.relationship_type, direction: 'reverse', reason: r.reason, priority: r.priority, product })
  }
  if (entries.length === 0) return null

  // Group by (type, direction), keep the DB priority order, cap each group.
  const groups = new Map<string, Entry[]>()
  for (const e of entries) {
    const key = `${e.type}:${e.direction}`
    const list = groups.get(key) ?? []
    if (list.some((x) => x.product.external_id === e.product.external_id)) continue
    list.push(e)
    groups.set(key, list)
  }
  const orderedKeys = Array.from(groups.keys()).sort((a, b) => {
    const [ta, da] = a.split(':'); const [tb, db] = b.split(':')
    if (da !== db) return da === 'forward' ? -1 : 1
    return TYPE_ORDER.indexOf(ta as EquipmentRelationshipType) - TYPE_ORDER.indexOf(tb as EquipmentRelationshipType)
  })

  return (
    <section className="mt-10">
      <div className="flex items-center gap-2 mb-1">
        <PlugZap className="h-5 w-5 text-accent" />
        <h2 className="text-lg font-bold text-foreground">Works with</h2>
      </div>
      <p className="text-sm text-muted-foreground mb-4">
        Matched by our SANS 10142-1 compatibility rules — voltage class, phase and current ratings all line up.
      </p>

      <div className="flex flex-col gap-6">
        {orderedKeys.map((key) => {
          const [type, direction] = key.split(':') as [string, 'forward' | 'reverse']
          const items = groups.get(key)!.slice(0, 4)
          const label = TYPE_LABELS[type]?.[direction] ?? 'Related products'
          return (
            <div key={key}>
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{label}</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {items.map((e) => (
                  <Link
                    key={e.product.external_id}
                    href={`/shop/${e.product.slug}`}
                    className="flex gap-3 p-3 rounded-xl border border-border bg-card hover:border-accent/50 hover:bg-muted/50 transition-colors group"
                  >
                    <div className="relative h-16 w-16 shrink-0 rounded-lg bg-muted overflow-hidden">
                      {e.product.images?.[0] ? (
                        <Image src={e.product.images[0]} alt={e.product.name} fill className="object-contain p-1.5" sizes="64px" />
                      ) : (
                        <div className="flex items-center justify-center h-full">
                          <Package className="h-6 w-6 text-muted-foreground/40" />
                        </div>
                      )}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-start justify-between gap-2">
                        <p className="text-sm font-medium text-foreground group-hover:text-primary transition-colors line-clamp-2">
                          {e.product.name}
                        </p>
                        {e.product.brand && <Badge variant="outline" className="shrink-0 text-[10px]">{e.product.brand}</Badge>}
                      </div>
                      <p className="text-sm font-semibold text-primary mt-0.5">{formatCurrency(e.product.price)}</p>
                      {e.reason && (
                        <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{e.reason}</p>
                      )}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          )
        })}
      </div>
    </section>
  )
}
