/**
 * SANS 10142-1:2024 Ed 3.2 — Table D.1: impedance of 600/1000 V SANS 1507
 * conductors, in Ω/km at 70 °C conductor temperature. Used by the PSCC
 * calculator (8.4.5: Zconductor = L × √(R²+X²) / 1000) and Annex D methods.
 * GENERATED by scripts/sans/gen-extra-tables.ts.
 */
export interface ConductorImpedance {
  size: number
  rAcCu: number | null
  rAcAl: number | null
  xAcCu: number | null
  xAcAl: number | null
  rDcCu: number | null
  rDcAl: number | null
}

export const CONDUCTOR_IMPEDANCE: ConductorImpedance[] = [
  { size: 1, rAcCu: 21.9, rAcAl: null, xAcCu: 0.107, xAcAl: null, rDcCu: 21.9, rDcAl: null },
  { size: 1.5, rAcCu: 14.48, rAcAl: null, xAcCu: 0.1, xAcAl: null, rDcCu: 14.48, rDcAl: null },
  { size: 2.5, rAcCu: 8.87, rAcAl: null, xAcCu: 0.095, xAcAl: null, rDcCu: 8.87, rDcAl: null },
  { size: 4, rAcCu: 5.52, rAcAl: null, xAcCu: 0.093, xAcAl: null, rDcCu: 5.52, rDcAl: null },
  { size: 6, rAcCu: 3.69, rAcAl: null, xAcCu: 0.09, xAcAl: null, rDcCu: 3.69, rDcAl: null },
  { size: 10, rAcCu: 2.19, rAcAl: null, xAcCu: 0.084, xAcAl: null, rDcCu: 2.19, rDcAl: null },
  { size: 16, rAcCu: 1.4, rAcAl: 2.3, xAcCu: 0.08, xAcAl: 0.08, rDcCu: 1.4, rDcAl: 2.2 },
  { size: 25, rAcCu: 0.88, rAcAl: 1.44, xAcCu: 0.079, xAcAl: 0.079, rDcCu: 0.87, rDcAl: 1.44 },
  { size: 35, rAcCu: 0.63, rAcAl: 1.03, xAcCu: 0.076, xAcAl: 0.076, rDcCu: 0.62, rDcAl: 1.03 },
  { size: 50, rAcCu: 0.44, rAcAl: 0.72, xAcCu: 0.076, xAcAl: 0.076, rDcCu: 0.44, rDcAl: 0.72 },
  { size: 70, rAcCu: 0.31, rAcAl: 0.52, xAcCu: 0.074, xAcAl: 0.074, rDcCu: 0.31, rDcAl: 0.51 },
  { size: 95, rAcCu: 0.23, rAcAl: 0.38, xAcCu: 0.073, xAcAl: 0.073, rDcCu: 0.23, rDcAl: 0.38 },
  { size: 120, rAcCu: 0.18, rAcAl: 0.3, xAcCu: 0.072, xAcAl: 0.072, rDcCu: 0.18, rDcAl: 0.3 },
  { size: 150, rAcCu: 0.15, rAcAl: 0.24, xAcCu: 0.072, xAcAl: 0.072, rDcCu: 0.15, rDcAl: 0.24 },
  { size: 185, rAcCu: 0.12, rAcAl: 0.2, xAcCu: 0.072, xAcAl: 0.072, rDcCu: 0.12, rDcAl: 0.19 },
  { size: 240, rAcCu: 0.095, rAcAl: 0.156, xAcCu: 0.072, xAcAl: 0.072, rDcCu: 0.091, rDcAl: 0.15 },
  { size: 300, rAcCu: 0.077, rAcAl: 0.127, xAcCu: 0.071, xAcAl: 0.071, rDcCu: 0.073, rDcAl: 0.12 },
  { size: 400, rAcCu: 0.06, rAcAl: 0.099, xAcCu: 0.071, xAcAl: 0.071, rDcCu: 0.055, rDcAl: 0.09 },
  { size: 500, rAcCu: 0.05, rAcAl: 0.083, xAcCu: 0.07, xAcAl: 0.07, rDcCu: 0.044, rDcAl: 0.072 },
  { size: 630, rAcCu: 0.043, rAcAl: 0.071, xAcCu: 0.069, xAcAl: 0.069, rDcCu: 0.035, rDcAl: 0.057 },
  { size: 800, rAcCu: 0.037, rAcAl: 0.061, xAcCu: 0.058, xAcAl: 0.058, rDcCu: 0.027, rDcAl: 0.045 },
  { size: 1000, rAcCu: 0.033, rAcAl: 0.054, xAcCu: 0.049, xAcAl: 0.049, rDcCu: 0.022, rDcAl: 0.036 },
]
