/**
 * SANS 10142-1:2024 Ed 3.2 current-capacity tables — second batch (aluminium,
 * buried and rubber-insulated). GENERATED by scripts/sans/gen-extra-tables.ts —
 * edit the generator, not this file. Table 6.6(a) (Al multicore, unarmoured)
 * is transcribed by hand in current-capacity.ts's extra list if present.
 */
import type { CcCableType } from './current-capacity'

/** Table 6.5(a) — Single-core PVC insulated cables, unarmoured, with or without sheath (SANS 1507 (all parts)) — Current-carrying capacity aluminium conductors (printed p. 104) */
const SINGLE_AL: CcCableType = {
  id: "single-al",
  label: "Single-core PVC, aluminium conductors",
  table: "6.5(a)",
  arrangements: [
    { id: "m1_2cab_1ph", label: "Installation method 1 (enclosed in conduit in thermally insulating wall, etc.) — two cables, single-phase a.c. or d.c.", phases: 1 as const },
    { id: "m1_3or4cab_3ph", label: "Installation method 1 (enclosed in conduit in thermally insulating wall, etc.) — three or four cables, three-phase a.c.", phases: 3 as const },
    { id: "m2_2cab_1ph", label: "Installation method 2 (enclosed in conduit on a wall or in trunking, etc.) — two cables, single-phase a.c. or d.c.", phases: 1 as const },
    { id: "m2_3or4cab_3ph", label: "Installation method 2 (enclosed in conduit on a wall or in trunking, etc.) — three or four cables, three-phase a.c.", phases: 3 as const },
    { id: "m3_2cab_1ph", label: "Installation method 3 (clipped direct) — two cables, single-phase a.c. or d.c. (flat and touching)", phases: 1 as const },
    { id: "m3_3or4cab_3ph", label: "Installation method 3 (clipped direct) — three or four cables, three-phase a.c. (flat and touching or trefoil)", phases: 3 as const },
    { id: "m4_2cab_1ph", label: "Installation method 4 (on a perforated cable tray, horizontal or vertical) — two cables, single-phase a.c. or d.c. (flat and touching)", phases: 1 as const },
    { id: "m4_3or4cab_3ph", label: "Installation method 4 (on a perforated cable tray, horizontal or vertical) — three or four cables, three-phase a.c. (flat and touching or trefoil)", phases: 3 as const },
    { id: "m5_horiz_flat_spaced", label: "Installation method 5 (in free air) — horizontal flat spaced — two cables, single-phase a.c. or d.c. or three cables, three-phase a.c.", phases: 1 as const },
    { id: "m5_vert_flat_spaced", label: "Installation method 5 (in free air) — vertical flat spaced — two cables, single-phase a.c. or d.c. or three cables, three-phase a.c.", phases: 1 as const },
    { id: "m5_trefoil", label: "Installation method 5 (in free air) — trefoil — three cables, trefoil three-phase a.c.", phases: 1 as const },
  ],
  rows: [
    { size: 50, values: { "m1_2cab_1ph": 93, "m1_3or4cab_3ph": 84, "m2_2cab_1ph": 118, "m2_3or4cab_3ph": 104, "m3_2cab_1ph": 134, "m3_3or4cab_3ph": 123, "m4_2cab_1ph": 144, "m4_3or4cab_3ph": 132, "m5_horiz_flat_spaced": 163, "m5_vert_flat_spaced": 148, "m5_trefoil": 128 } },
    { size: 70, values: { "m1_2cab_1ph": 118, "m1_3or4cab_3ph": 107, "m2_2cab_1ph": 150, "m2_3or4cab_3ph": 133, "m3_2cab_1ph": 172, "m3_3or4cab_3ph": 159, "m4_2cab_1ph": 185, "m4_3or4cab_3ph": 169, "m5_horiz_flat_spaced": 210, "m5_vert_flat_spaced": 191, "m5_trefoil": 165 } },
    { size: 95, values: { "m1_2cab_1ph": 142, "m1_3or4cab_3ph": 120, "m2_2cab_1ph": 181, "m2_3or4cab_3ph": 161, "m3_2cab_1ph": 210, "m3_3or4cab_3ph": 194, "m4_2cab_1ph": 225, "m4_3or4cab_3ph": 206, "m5_horiz_flat_spaced": 256, "m5_vert_flat_spaced": 234, "m5_trefoil": 203 } },
    { size: 120, values: { "m1_2cab_1ph": 164, "m1_3or4cab_3ph": 140, "m2_2cab_1ph": 210, "m2_3or4cab_3ph": 186, "m3_2cab_1ph": 245, "m3_3or4cab_3ph": 226, "m4_2cab_1ph": 261, "m4_3or4cab_3ph": 240, "m5_horiz_flat_spaced": 298, "m5_vert_flat_spaced": 273, "m5_trefoil": 237 } },
    { size: 150, values: { "m1_2cab_1ph": 189, "m1_3or4cab_3ph": 170, "m2_2cab_1ph": 234, "m2_3or4cab_3ph": 204, "m3_2cab_1ph": 283, "m3_3or4cab_3ph": 261, "m4_2cab_1ph": 301, "m4_3or4cab_3ph": 277, "m5_horiz_flat_spaced": 344, "m5_vert_flat_spaced": 317, "m5_trefoil": 274 } },
    { size: 185, values: { "m1_2cab_1ph": 215, "m1_3or4cab_3ph": 194, "m2_2cab_1ph": 266, "m2_3or4cab_3ph": 230, "m3_2cab_1ph": 324, "m3_3or4cab_3ph": 299, "m4_2cab_1ph": 344, "m4_3or4cab_3ph": 317, "m5_horiz_flat_spaced": 394, "m5_vert_flat_spaced": 364, "m5_trefoil": 316 } },
    { size: 240, values: { "m1_2cab_1ph": 252, "m1_3or4cab_3ph": 227, "m2_2cab_1ph": 312, "m2_3or4cab_3ph": 269, "m3_2cab_1ph": 384, "m3_3or4cab_3ph": 354, "m4_2cab_1ph": 407, "m4_3or4cab_3ph": 375, "m5_horiz_flat_spaced": 466, "m5_vert_flat_spaced": 432, "m5_trefoil": 375 } },
    { size: 300, values: { "m1_2cab_1ph": 289, "m1_3or4cab_3ph": 261, "m2_2cab_1ph": 358, "m2_3or4cab_3ph": 306, "m3_2cab_1ph": 444, "m3_3or4cab_3ph": 410, "m4_2cab_1ph": 469, "m4_3or4cab_3ph": 433, "m5_horiz_flat_spaced": 538, "m5_vert_flat_spaced": 501, "m5_trefoil": 435 } },
    { size: 380, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": 413, "m2_3or4cab_3ph": 352, "m3_2cab_1ph": 511, "m3_3or4cab_3ph": 472, "m4_2cab_1ph": 543, "m4_3or4cab_3ph": 502, "m5_horiz_flat_spaced": 625, "m5_vert_flat_spaced": 584, "m5_trefoil": 507 } },
    { size: 480, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": 477, "m2_3or4cab_3ph": 405, "m3_2cab_1ph": 591, "m3_3or4cab_3ph": 546, "m4_2cab_1ph": 629, "m4_3or4cab_3ph": 582, "m5_horiz_flat_spaced": 726, "m5_vert_flat_spaced": 680, "m5_trefoil": 590 } },
    { size: 600, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": 545, "m2_3or4cab_3ph": 462, "m3_2cab_1ph": 679, "m3_3or4cab_3ph": 626, "m4_2cab_1ph": 722, "m4_3or4cab_3ph": 669, "m5_horiz_flat_spaced": 837, "m5_vert_flat_spaced": 787, "m5_trefoil": 680 } },
    { size: 740, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": null, "m2_3or4cab_3ph": null, "m3_2cab_1ph": 771, "m3_3or4cab_3ph": 709, "m4_2cab_1ph": 820, "m4_3or4cab_3ph": 761, "m5_horiz_flat_spaced": 956, "m5_vert_flat_spaced": 902, "m5_trefoil": 776 } },
    { size: 960, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": null, "m2_3or4cab_3ph": null, "m3_2cab_1ph": 900, "m3_3or4cab_3ph": 823, "m4_2cab_1ph": 953, "m4_3or4cab_3ph": 886, "m5_horiz_flat_spaced": 1125, "m5_vert_flat_spaced": 1066, "m5_trefoil": 907 } },
    { size: 1200, values: { "m1_2cab_1ph": null, "m1_3or4cab_3ph": null, "m2_2cab_1ph": null, "m2_3or4cab_3ph": null, "m3_2cab_1ph": 1022, "m3_3or4cab_3ph": 926, "m4_2cab_1ph": 1073, "m4_3or4cab_3ph": 999, "m5_horiz_flat_spaced": 1293, "m5_vert_flat_spaced": 1229, "m5_trefoil": 1026 } },
  ],
}

/** Table 6.7(a) — Multicore PVC insulated armoured cables (SANS 1507 (all parts)) — Current-carrying capacity aluminium conductors (printed p. 108) */
const MULTI_AL_SWA: CcCableType = {
  id: "multi-al-swa",
  label: "Multicore PVC, armoured (SWA), aluminium",
  table: "6.7(a)",
  arrangements: [
    { id: "clipped_1ph", label: "Installation method 3 (clipped direct) — one two-core cable, single-phase a.c. or d.c.", phases: 1 as const },
    { id: "clipped_3ph", label: "Installation method 3 (clipped direct) — one three-core or four-core cable, three-phase a.c.", phases: 3 as const },
    { id: "tray_freeair_1ph", label: "Installation method 4 (perforated cable tray) or method 6 (free air) — one two-core cable, single-phase a.c. or d.c.", phases: 1 as const },
    { id: "tray_freeair_3ph", label: "Installation method 4 (perforated cable tray) or method 6 (free air) — one three-core or four-core cable, three-phase a.c.", phases: 3 as const },
  ],
  rows: [
    { size: 16, values: { "clipped_1ph": 68, "clipped_3ph": 58, "tray_freeair_1ph": 71, "tray_freeair_3ph": 61 } },
    { size: 25, values: { "clipped_1ph": 89, "clipped_3ph": 76, "tray_freeair_1ph": 94, "tray_freeair_3ph": 80 } },
    { size: 35, values: { "clipped_1ph": 109, "clipped_3ph": 94, "tray_freeair_1ph": 115, "tray_freeair_3ph": 99 } },
    { size: 50, values: { "clipped_1ph": 131, "clipped_3ph": 113, "tray_freeair_1ph": 139, "tray_freeair_3ph": 119 } },
    { size: 70, values: { "clipped_1ph": 165, "clipped_3ph": 143, "tray_freeair_1ph": 175, "tray_freeair_3ph": 151 } },
    { size: 95, values: { "clipped_1ph": 199, "clipped_3ph": 174, "tray_freeair_1ph": 211, "tray_freeair_3ph": 186 } },
    { size: 120, values: { "clipped_1ph": null, "clipped_3ph": 202, "tray_freeair_1ph": null, "tray_freeair_3ph": 216 } },
    { size: 150, values: { "clipped_1ph": null, "clipped_3ph": 232, "tray_freeair_1ph": null, "tray_freeair_3ph": 250 } },
    { size: 185, values: { "clipped_1ph": null, "clipped_3ph": 265, "tray_freeair_1ph": null, "tray_freeair_3ph": 287 } },
    { size: 240, values: { "clipped_1ph": null, "clipped_3ph": 312, "tray_freeair_1ph": null, "tray_freeair_3ph": 342 } },
    { size: 300, values: { "clipped_1ph": null, "clipped_3ph": 360, "tray_freeair_1ph": null, "tray_freeair_3ph": 399 } },
  ],
}

/** Table 6.8 — Multicore PVC insulated armoured cables buried directly in the ground (SANS 1507 (all parts)) — Current-carrying capacity (printed p. 110) */
const BURIED_SWA: CcCableType = {
  id: "buried-swa",
  label: "Multicore PVC armoured, buried (direct / in ducts)",
  table: "6.8",
  arrangements: [
    { id: "cu_ground_2core", label: "Copper — cables buried in the ground — two-core", phases: 1 as const },
    { id: "cu_ground_3_4core", label: "Copper — cables buried in the ground — three-core or four-core", phases: 3 as const },
    { id: "cu_ducts_2core", label: "Copper — cables in pipes or ducts buried in the ground — two-core", phases: 1 as const },
    { id: "cu_ducts_3_4core", label: "Copper — cables in pipes or ducts buried in the ground — three-core or four-core", phases: 3 as const },
    { id: "al_ground_2core", label: "Aluminium — cables buried in the ground — two-core", phases: 1 as const },
    { id: "al_ground_3_4core", label: "Aluminium — cables buried in the ground — three-core or four-core", phases: 3 as const },
    { id: "al_ducts_2core", label: "Aluminium — cables in pipes or ducts buried in the ground — two-core", phases: 1 as const },
    { id: "al_ducts_3_4core", label: "Aluminium — cables in pipes or ducts buried in the ground — three-core or four-core", phases: 3 as const },
  ],
  rows: [
    { size: 1.5, values: { "cu_ground_2core": 29, "cu_ground_3_4core": 24, "cu_ducts_2core": 23, "cu_ducts_3_4core": 20, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 2.5, values: { "cu_ground_2core": 37, "cu_ground_3_4core": 32, "cu_ducts_2core": 31, "cu_ducts_3_4core": 26, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 4, values: { "cu_ground_2core": 50, "cu_ground_3_4core": 42, "cu_ducts_2core": 41, "cu_ducts_3_4core": 34, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 6, values: { "cu_ground_2core": 62, "cu_ground_3_4core": 53, "cu_ducts_2core": 51, "cu_ducts_3_4core": 43, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 10, values: { "cu_ground_2core": 83, "cu_ground_3_4core": 70, "cu_ducts_2core": 68, "cu_ducts_3_4core": 58, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 16, values: { "cu_ground_2core": 107, "cu_ground_3_4core": 91, "cu_ducts_2core": 88, "cu_ducts_3_4core": 75, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
    { size: 25, values: { "cu_ground_2core": 142, "cu_ground_3_4core": 119, "cu_ducts_2core": 116, "cu_ducts_3_4core": 96, "al_ground_2core": 106, "al_ground_3_4core": 90, "al_ducts_2core": 86, "al_ducts_3_4core": 73 } },
    { size: 35, values: { "cu_ground_2core": 171, "cu_ground_3_4core": 143, "cu_ducts_2core": 139, "cu_ducts_3_4core": 116, "al_ground_2core": 128, "al_ground_3_4core": 108, "al_ducts_2core": 104, "al_ducts_3_4core": 87 } },
    { size: 50, values: { "cu_ground_2core": 203, "cu_ground_3_4core": 169, "cu_ducts_2core": 165, "cu_ducts_3_4core": 138, "al_ground_2core": 151, "al_ground_3_4core": 129, "al_ducts_2core": 123, "al_ducts_3_4core": 104 } },
    { size: 70, values: { "cu_ground_2core": 249, "cu_ground_3_4core": 210, "cu_ducts_2core": 203, "cu_ducts_3_4core": 171, "al_ground_2core": 188, "al_ground_3_4core": 158, "al_ducts_2core": 153, "al_ducts_3_4core": 130 } },
    { size: 95, values: { "cu_ground_2core": 299, "cu_ground_3_4core": 251, "cu_ducts_2core": 244, "cu_ducts_3_4core": 205, "al_ground_2core": 225, "al_ground_3_4core": 192, "al_ducts_2core": 184, "al_ducts_3_4core": 157 } },
    { size: 120, values: { "cu_ground_2core": 339, "cu_ground_3_4core": 285, "cu_ducts_2core": 278, "cu_ducts_3_4core": 234, "al_ground_2core": null, "al_ground_3_4core": 219, "al_ducts_2core": null, "al_ducts_3_4core": 179 } },
    { size: 150, values: { "cu_ground_2core": 380, "cu_ground_3_4core": 320, "cu_ducts_2core": 311, "cu_ducts_3_4core": 263, "al_ground_2core": null, "al_ground_3_4core": 245, "al_ducts_2core": null, "al_ducts_3_4core": 201 } },
    { size: 185, values: { "cu_ground_2core": 430, "cu_ground_3_4core": 361, "cu_ducts_2core": 354, "cu_ducts_3_4core": 298, "al_ground_2core": null, "al_ground_3_4core": 278, "al_ducts_2core": null, "al_ducts_3_4core": 229 } },
    { size: 240, values: { "cu_ground_2core": 496, "cu_ground_3_4core": 416, "cu_ducts_2core": 410, "cu_ducts_3_4core": 344, "al_ground_2core": null, "al_ground_3_4core": 324, "al_ducts_2core": null, "al_ducts_3_4core": 268 } },
    { size: 300, values: { "cu_ground_2core": 554, "cu_ground_3_4core": 465, "cu_ducts_2core": 459, "cu_ducts_3_4core": 385, "al_ground_2core": null, "al_ground_3_4core": 366, "al_ducts_2core": null, "al_ducts_3_4core": 304 } },
    { size: 400, values: { "cu_ground_2core": 624, "cu_ground_3_4core": 522, "cu_ducts_2core": 517, "cu_ducts_3_4core": 441, "al_ground_2core": null, "al_ground_3_4core": null, "al_ducts_2core": null, "al_ducts_3_4core": null } },
  ],
}

/** Table 6.9(a) — 85 °C or 150 °C rubber-insulated and silicon-rubber-insulated flexible cables (SANS 1574-5) — Current-carrying capacity copper conductors (printed p. 111) */
const RUBBER_FLEX: CcCableType = {
  id: "rubber-flex",
  label: "85/150 °C rubber & silicone-rubber insulated, copper",
  table: "6.9(a)",
  arrangements: [
    { id: "dc_1ph_2core", label: "D.C. or single-phase a.c. (one two-core cable, with or without protective conductor)", phases: 1 as const },
    { id: "ac_3ph", label: "Three-phase a.c. (one three-core, four-core or five-core cable)", phases: 3 as const },
    { id: "dc_1ph_2single", label: "Single-phase a.c. or d.c., two single-core cables, touching", phases: 1 as const },
  ],
  rows: [
    { size: 4, values: { "dc_1ph_2core": 41, "ac_3ph": 36, "dc_1ph_2single": null } },
    { size: 6, values: { "dc_1ph_2core": 53, "ac_3ph": 47, "dc_1ph_2single": null } },
    { size: 10, values: { "dc_1ph_2core": 73, "ac_3ph": 64, "dc_1ph_2single": null } },
    { size: 16, values: { "dc_1ph_2core": 99, "ac_3ph": 86, "dc_1ph_2single": null } },
    { size: 25, values: { "dc_1ph_2core": 131, "ac_3ph": 114, "dc_1ph_2single": null } },
    { size: 35, values: { "dc_1ph_2core": null, "ac_3ph": 140, "dc_1ph_2single": 192 } },
    { size: 50, values: { "dc_1ph_2core": null, "ac_3ph": 170, "dc_1ph_2single": 240 } },
    { size: 70, values: { "dc_1ph_2core": null, "ac_3ph": 216, "dc_1ph_2single": 297 } },
    { size: 95, values: { "dc_1ph_2core": null, "ac_3ph": 262, "dc_1ph_2single": 354 } },
    { size: 400, values: { "dc_1ph_2core": null, "ac_3ph": null, "dc_1ph_2single": 885 } },
    { size: 500, values: { "dc_1ph_2core": null, "ac_3ph": null, "dc_1ph_2single": 1017 } },
    { size: 630, values: { "dc_1ph_2core": null, "ac_3ph": null, "dc_1ph_2single": 1190 } },
  ],
}

export const CC_CABLE_TYPES_EXTRA: CcCableType[] = [SINGLE_AL, MULTI_AL_SWA, BURIED_SWA, RUBBER_FLEX]
