/**
 * SANS 10142-1:2024 Ed 3.2 — buried-cable correction factors.
 * Table 6.11 (soil temperature, 25 °C base) and table 6.12 (soil thermal
 * resistivity). GENERATED by scripts/sans/gen-extra-tables.ts.
 */
export const SOIL_TEMP_FACTORS: { soilTempC: number; factor: number | null }[] = [
  { soilTempC: 10, factor: 1.15 },
  { soilTempC: 15, factor: 1.11 },
  { soilTempC: 20, factor: 1.05 },
  { soilTempC: 25, factor: 1 },
  { soilTempC: 30, factor: 0.94 },
  { soilTempC: 35, factor: 0.88 },
  { soilTempC: 40, factor: 0.82 },
]

export const SOIL_RESISTIVITY_FACTORS: { resistivityKmW: number; buriedDirect: number | null; inPipes: number | null }[] = [
  { resistivityKmW: 0.7, buriedDirect: 1.17, inPipes: 1.07 },
  { resistivityKmW: 0.8, buriedDirect: 1.13, inPipes: 1.05 },
  { resistivityKmW: 0.9, buriedDirect: 1.09, inPipes: 1.04 },
  { resistivityKmW: 1, buriedDirect: 1.06, inPipes: 1.02 },
  { resistivityKmW: 1.2, buriedDirect: 1, inPipes: 1 },
  { resistivityKmW: 1.5, buriedDirect: 0.93, inPipes: 0.96 },
  { resistivityKmW: 2, buriedDirect: 0.83, inPipes: 0.91 },
  { resistivityKmW: 2.5, buriedDirect: 0.76, inPipes: 0.87 },
  { resistivityKmW: 3, buriedDirect: 0.71, inPipes: 0.83 },
  { resistivityKmW: 3.5, buriedDirect: 0.65, inPipes: 0.8 },
  { resistivityKmW: 4, buriedDirect: 0.61, inPipes: 0.77 },
]
