/**
 * SANS 10142-1:2024 Ed 3.2 voltage-drop tables — second batch (aluminium and
 * rubber-insulated). GENERATED by scripts/sans/gen-extra-tables.ts from the
 * agent-transcribed, self-checked extraction JSON — edit the generator, not this file.
 */
import type { VdCableType } from './voltage-drop'

/** Table 6.5(b) — Single-core PVC insulated cables, unarmoured, with or without sheath (SANS 1507 (all parts)) — Voltage drop (per ampere per metre) aluminium conductors (printed p. 105) */
const SINGLE_AL: VdCableType = {
  id: "single-al",
  label: "Single-core PVC, aluminium conductors",
  table: "6.5(b)",
  clauseRef: "6.2.7",
  arrangements: [
    { id: 'dc', label: 'd.c.', phases: 0 as const },
    { id: "1ph_m12", label: "Single-phase — methods 1 & 2 (enclosed)", phases: 1 as const },
    { id: "1ph_m34", label: "Single-phase — methods 3 & 4 (clipped / tray, touching)", phases: 1 as const },
    { id: "1ph_m5", label: "Single-phase — method 5 (spaced, free air)", phases: 1 as const },
    { id: "3ph_m12", label: "Three-phase — methods 1 & 2 (enclosed)", phases: 3 as const },
    { id: "3ph_trefoil", label: "Three-phase — trefoil", phases: 3 as const },
    { id: "3ph_flat_touch", label: "Three-phase — flat & touching (methods 3 & 4)", phases: 3 as const },
    { id: "3ph_flat_spaced", label: "Three-phase — flat, spaced (method 5)", phases: 3 as const },
  ],
  rows: [
    { size: 50, values: { dc: 1.55, "1ph_m12": { r: 1.6, x: 0.3, z: 1.6 }, "1ph_m34": { r: 1.55, x: 0.19, z: 1.55 }, "1ph_m5": { r: 1.55, x: 0.28, z: 1.55 }, "3ph_m12": { r: 1.35, x: 0.26, z: 1.4 }, "3ph_trefoil": { r: 1.35, x: 0.165, z: 1.35 }, "3ph_flat_touch": { r: 1.35, x: 0.24, z: 1.35 }, "3ph_flat_spaced": { r: 1.35, x: 0.32, z: 1.4 } } },
    { size: 70, values: { dc: 1.05, "1ph_m12": { r: 1.1, x: 0.3, z: 1.15 }, "1ph_m34": { r: 1.05, x: 0.185, z: 1.05 }, "1ph_m5": { r: 1.05, x: 0.27, z: 1.1 }, "3ph_m12": { r: 0.94, x: 0.26, z: 0.97 }, "3ph_trefoil": { r: 0.91, x: 0.16, z: 0.92 }, "3ph_flat_touch": { r: 0.91, x: 0.24, z: 0.94 }, "3ph_flat_spaced": { r: 0.91, x: 0.31, z: 0.96 } } },
    { size: 95, values: { dc: 0.77, "1ph_m12": { r: 0.81, x: 0.29, z: 0.86 }, "1ph_m34": { r: 0.77, x: 0.185, z: 0.79 }, "1ph_m5": { r: 0.77, x: 0.27, z: 0.82 }, "3ph_m12": { r: 0.7, x: 0.25, z: 0.74 }, "3ph_trefoil": { r: 0.67, x: 0.16, z: 0.69 }, "3ph_flat_touch": { r: 0.67, x: 0.23, z: 0.71 }, "3ph_flat_spaced": { r: 0.67, x: 0.31, z: 0.74 } } },
    { size: 120, values: { dc: 0.61, "1ph_m12": { r: 0.64, x: 0.29, z: 0.7 }, "1ph_m34": { r: 0.61, x: 0.18, z: 0.64 }, "1ph_m5": { r: 0.61, x: 0.27, z: 0.67 }, "3ph_m12": { r: 0.55, x: 0.25, z: 0.61 }, "3ph_trefoil": { r: 0.53, x: 0.155, z: 0.55 }, "3ph_flat_touch": { r: 0.53, x: 0.23, z: 0.58 }, "3ph_flat_spaced": { r: 0.53, x: 0.31, z: 0.61 } } },
    { size: 150, values: { dc: 0.49, "1ph_m12": { r: 0.51, x: 0.28, z: 0.59 }, "1ph_m34": { r: 0.49, x: 0.175, z: 0.52 }, "1ph_m5": { r: 0.49, x: 0.26, z: 0.55 }, "3ph_m12": { r: 0.45, x: 0.24, z: 0.51 }, "3ph_trefoil": { r: 0.42, x: 0.155, z: 0.45 }, "3ph_flat_touch": { r: 0.42, x: 0.23, z: 0.48 }, "3ph_flat_spaced": { r: 0.42, x: 0.3, z: 0.52 } } },
    { size: 185, values: { dc: 0.39, "1ph_m12": { r: 0.42, x: 0.28, z: 0.5 }, "1ph_m34": { r: 0.4, x: 0.175, z: 0.43 }, "1ph_m5": { r: 0.39, x: 0.26, z: 0.47 }, "3ph_m12": { r: 0.36, x: 0.24, z: 0.44 }, "3ph_trefoil": { r: 0.34, x: 0.15, z: 0.37 }, "3ph_flat_touch": { r: 0.34, x: 0.23, z: 0.41 }, "3ph_flat_spaced": { r: 0.34, x: 0.3, z: 0.46 } } },
    { size: 240, values: { dc: 0.3, "1ph_m12": { r: 0.32, x: 0.27, z: 0.42 }, "1ph_m34": { r: 0.3, x: 0.17, z: 0.35 }, "1ph_m5": { r: 0.3, x: 0.26, z: 0.4 }, "3ph_m12": { r: 0.28, x: 0.24, z: 0.37 }, "3ph_trefoil": { r: 0.26, x: 0.15, z: 0.3 }, "3ph_flat_touch": { r: 0.26, x: 0.22, z: 0.35 }, "3ph_flat_spaced": { r: 0.26, x: 0.3, z: 0.4 } } },
    { size: 300, values: { dc: 0.24, "1ph_m12": { r: 0.26, x: 0.27, z: 0.37 }, "1ph_m34": { r: 0.24, x: 0.17, z: 0.3 }, "1ph_m5": { r: 0.24, x: 0.26, z: 0.35 }, "3ph_m12": { r: 0.23, x: 0.23, z: 0.32 }, "3ph_trefoil": { r: 0.21, x: 0.145, z: 0.26 }, "3ph_flat_touch": { r: 0.21, x: 0.22, z: 0.31 }, "3ph_flat_spaced": { r: 0.21, x: 0.3, z: 0.36 } } },
    { size: 380, values: { dc: 0.19, "1ph_m12": { r: 0.22, x: 0.27, z: 0.35 }, "1ph_m34": { r: 0.195, x: 0.165, z: 0.26 }, "1ph_m5": { r: 0.195, x: 0.25, z: 0.32 }, "3ph_m12": { r: 0.19, x: 0.23, z: 0.3 }, "3ph_trefoil": { r: 0.17, x: 0.145, z: 0.22 }, "3ph_flat_touch": { r: 0.17, x: 0.22, z: 0.28 }, "3ph_flat_spaced": { r: 0.17, x: 0.29, z: 0.34 } } },
    { size: 480, values: { dc: 0.15, "1ph_m12": { r: 0.18, x: 0.26, z: 0.32 }, "1ph_m34": { r: 0.155, x: 0.165, z: 0.23 }, "1ph_m5": { r: 0.155, x: 0.25, z: 0.29 }, "3ph_m12": { r: 0.155, x: 0.23, z: 0.27 }, "3ph_trefoil": { r: 0.14, x: 0.14, z: 0.195 }, "3ph_flat_touch": { r: 0.14, x: 0.22, z: 0.26 }, "3ph_flat_spaced": { r: 0.135, x: 0.29, z: 0.32 } } },
    { size: 600, values: { dc: 0.12, "1ph_m12": { r: 0.15, x: 0.27, z: 0.31 }, "1ph_m34": { r: 0.13, x: 0.16, z: 0.21 }, "1ph_m5": { r: 0.125, x: 0.25, z: 0.28 }, "3ph_m12": { r: 0.125, x: 0.22, z: 0.26 }, "3ph_trefoil": { r: 0.11, x: 0.14, z: 0.18 }, "3ph_flat_touch": { r: 0.11, x: 0.22, z: 0.24 }, "3ph_flat_spaced": { r: 0.11, x: 0.29, z: 0.31 } } },
    { size: 740, values: { dc: 0.099, "1ph_m12": null, "1ph_m34": { r: 0.105, x: 0.16, z: 0.19 }, "1ph_m5": { r: 0.1, x: 0.25, z: 0.27 }, "3ph_m12": null, "3ph_trefoil": { r: 0.094, x: 0.135, z: 0.165 }, "3ph_flat_touch": { r: 0.094, x: 0.21, z: 0.23 }, "3ph_flat_spaced": { r: 0.089, x: 0.29, z: 0.3 } } },
    { size: 960, values: { dc: 0.075, "1ph_m12": null, "1ph_m34": { r: 0.086, x: 0.155, z: 0.18 }, "1ph_m5": { r: 0.082, x: 0.24, z: 0.26 }, "3ph_m12": null, "3ph_trefoil": { r: 0.077, x: 0.135, z: 0.155 }, "3ph_flat_touch": { r: 0.077, x: 0.21, z: 0.22 }, "3ph_flat_spaced": { r: 0.071, x: 0.29, z: 0.29 } } },
    { size: 1200, values: { dc: 0.06, "1ph_m12": null, "1ph_m34": { r: 0.074, x: 0.155, z: 0.17 }, "1ph_m5": { r: 0.068, x: 0.24, z: 0.25 }, "3ph_m12": null, "3ph_trefoil": { r: 0.066, x: 0.135, z: 0.15 }, "3ph_flat_touch": { r: 0.066, x: 0.21, z: 0.22 }, "3ph_flat_spaced": { r: 0.059, x: 0.28, z: 0.29 } } },
  ],
}

/** Table 6.6(b) — Multicore PVC insulated cables, unarmoured (SANS 1507 (all parts)) — Voltage drop (per ampere per metre) aluminium conductors (printed p. 107) */
const MULTI_AL: VdCableType = {
  id: "multi-al",
  label: "Multicore PVC, unarmoured, aluminium",
  table: "6.6(b)",
  clauseRef: "6.2.7",
  arrangements: [
    { id: 'dc', label: 'd.c.', phases: 0 as const },
    { id: "1ph", label: "Single-phase — two-core cable", phases: 1 as const },
    { id: "3ph", label: "Three-phase — three/four-core cable", phases: 3 as const },
  ],
  rows: [
    { size: 16, values: { dc: 4.5, "1ph": 4.5, "3ph": 3.9 } },
    { size: 25, values: { dc: 2.9, "1ph": { r: 2.9, x: 0.175, z: 2.9 }, "3ph": { r: 2.5, x: 0.15, z: 2.5 } } },
    { size: 35, values: { dc: 2.1, "1ph": { r: 2.1, x: 0.17, z: 2.1 }, "3ph": { r: 1.8, x: 0.15, z: 1.8 } } },
    { size: 50, values: { dc: 1.55, "1ph": { r: 1.55, x: 0.17, z: 1.55 }, "3ph": { r: 1.35, x: 0.145, z: 1.35 } } },
    { size: 70, values: { dc: 1.05, "1ph": { r: 1.05, x: 0.165, z: 1.05 }, "3ph": { r: 0.9, x: 0.14, z: 0.92 } } },
    { size: 95, values: { dc: 0.77, "1ph": { r: 0.77, x: 0.16, z: 0.79 }, "3ph": { r: 0.67, x: 0.14, z: 0.68 } } },
    { size: 120, values: { dc: null, "1ph": null, "3ph": { r: 0.53, x: 0.135, z: 0.55 } } },
    { size: 150, values: { dc: null, "1ph": null, "3ph": { r: 0.42, x: 0.135, z: 0.44 } } },
    { size: 185, values: { dc: null, "1ph": null, "3ph": { r: 0.34, x: 0.135, z: 0.37 } } },
    { size: 240, values: { dc: null, "1ph": null, "3ph": { r: 0.26, x: 0.13, z: 0.3 } } },
    { size: 300, values: { dc: null, "1ph": null, "3ph": { r: 0.21, x: 0.13, z: 0.25 } } },
  ],
}

/** Table 6.7(b) — Multicore PVC insulated armoured cables (SANS 1507 (all parts)) — Voltage drop (per ampere per metre) aluminium conductors (printed p. 109) */
const MULTI_AL_SWA: VdCableType = {
  id: "multi-al-swa",
  label: "Multicore PVC, armoured (SWA), aluminium",
  table: "6.7(b)",
  clauseRef: "6.2.7",
  arrangements: [
    { id: 'dc', label: 'd.c.', phases: 0 as const },
    { id: "1ph", label: "Single-phase — two-core cable", phases: 1 as const },
    { id: "3ph", label: "Three-phase — three/four-core cable", phases: 3 as const },
  ],
  rows: [
    { size: 16, values: { dc: 4.5, "1ph": 4.5, "3ph": 3.9 } },
    { size: 25, values: { dc: 2.9, "1ph": { r: 2.9, x: 0.175, z: 2.9 }, "3ph": { r: 2.5, x: 0.15, z: 2.5 } } },
    { size: 35, values: { dc: 2.1, "1ph": { r: 2.1, x: 0.17, z: 2.1 }, "3ph": { r: 1.8, x: 0.15, z: 1.8 } } },
    { size: 50, values: { dc: 1.55, "1ph": { r: 1.55, x: 0.17, z: 1.55 }, "3ph": { r: 1.35, x: 0.145, z: 1.35 } } },
    { size: 70, values: { dc: 1.05, "1ph": { r: 1.05, x: 0.165, z: 1.05 }, "3ph": { r: 0.9, x: 0.14, z: 0.92 } } },
    { size: 95, values: { dc: 0.77, "1ph": { r: 0.77, x: 0.16, z: 0.79 }, "3ph": { r: 0.67, x: 0.14, z: 0.68 } } },
    { size: 120, values: { dc: null, "1ph": null, "3ph": { r: 0.53, x: 0.135, z: 0.55 } } },
    { size: 150, values: { dc: null, "1ph": null, "3ph": { r: 0.42, x: 0.135, z: 0.44 } } },
    { size: 185, values: { dc: null, "1ph": null, "3ph": { r: 0.34, x: 0.135, z: 0.37 } } },
    { size: 240, values: { dc: null, "1ph": null, "3ph": { r: 0.26, x: 0.13, z: 0.3 } } },
    { size: 300, values: { dc: null, "1ph": null, "3ph": { r: 0.21, x: 0.13, z: 0.25 } } },
  ],
}

/** Table 6.9(b) — 85 °C or 150 °C rubber-insulated and silicon-rubber-insulated flexible cables — Voltage drop (per ampere per metre) copper conductors (SANS 1574-5) (printed p. 113) */
const RUBBER_FLEX: VdCableType = {
  id: "rubber-flex",
  label: "85/150 °C rubber & silicone-rubber insulated, copper",
  table: "6.9(b)",
  clauseRef: "6.2.7",
  arrangements: [
    { id: 'dc', label: 'd.c.', phases: 0 as const },
    { id: "1ph_2core", label: "Single-phase — two-core cable", phases: 1 as const },
    { id: "3ph", label: "Three-phase — three/four-core cable", phases: 3 as const },
    { id: "1ph_2single", label: "Single-phase — two single cables", phases: 1 as const },
  ],
  rows: [
    { size: 4, values: { dc: 13, "1ph_2core": 13, "3ph": 11, "1ph_2single": null } },
    { size: 6, values: { dc: 8.4, "1ph_2core": 8.4, "3ph": 7.3, "1ph_2single": null } },
    { size: 10, values: { dc: 5, "1ph_2core": 5, "3ph": 4.3, "1ph_2single": null } },
    { size: 16, values: { dc: 3.1, "1ph_2core": 3.1, "3ph": 2.7, "1ph_2single": null } },
    { size: 25, values: { dc: 2, "1ph_2core": { r: 2, x: 0.175, z: 2 }, "3ph": { r: 1.7, x: 0.15, z: 1.7 }, "1ph_2single": null } },
    { size: 35, values: { dc: 1.42, "1ph_2core": null, "3ph": { r: 1.2, x: 0.15, z: 1.2 }, "1ph_2single": { r: 1.42, x: 0.21, z: 1.43 } } },
    { size: 50, values: { dc: 0.99, "1ph_2core": null, "3ph": { r: 0.9, x: 0.145, z: 0.91 }, "1ph_2single": { r: 0.99, x: 0.21, z: 1.01 } } },
    { size: 70, values: { dc: 0.7, "1ph_2core": null, "3ph": { r: 0.61, x: 0.14, z: 0.63 }, "1ph_2single": { r: 0.7, x: 0.2, z: 0.72 } } },
    { size: 95, values: { dc: 0.53, "1ph_2core": null, "3ph": { r: 0.46, x: 0.135, z: 0.48 }, "1ph_2single": { r: 0.53, x: 0.195, z: 0.56 } } },
  ],
}

export const VD_CABLE_TYPES_EXTRA: VdCableType[] = [SINGLE_AL, MULTI_AL, MULTI_AL_SWA, RUBBER_FLEX]
